### ISSUE TITLE
Mouse Gestures appearance on certain websites is malformed

### ISSUE THREAD

**Issue by redactedscribe** [yhchiu/smartup#4]
E.g on https://brave.com/latest/ the appearance of the Mouse Gestures overlay is much larger (padded) than on all other sites.

**Bug (brave.com):**

![Image](https://github.com/user-attachments/assets/4f9903f9-3529-4ee1-8482-8e229e52afbb)

**Should look like (options.html; but also all other websites):**

![Image](https://github.com/user-attachments/assets/3214d45a-19dd-4f3a-8f9d-e97e3c2396af)

**Comment by yhchiu** [comment]
I’m not completely sure what the issue is yet. Could you please provide the exact steps you took before the issue happened?

**Comment by redactedscribe** [comment]
1. ReSeT config.
2. Mouse Gesture > Appearance > Enable: Show next all possible actions
3. Visit https://brave.com/latest/ and refresh.
4. Draw a mouse gesture.

Compare this with a different website and you will see the difference as is shown in the screenshots above.

If you don't see the issue, it may be due to some conflicting extensions I have but I had a quick look and it doesn't look like there should be anything interfering (not tested with a blank profile). I am also using the Brave browser if that matters.

**Comment by yhchiu** [comment]
This has been fixed. Please refer to commit f81fdc6.

**Comment by redactedscribe** [comment]
Unfortunately still broken:

![Image](https://github.com/user-attachments/assets/e1971d24-aa72-447e-82f5-70958cfb9a2e)

**Comment by yhchiu** [comment]
This has been fixed. Please refer to commit 59bf552.

**Comment by redactedscribe** [comment]
I can confirm that it's working from commit 2796769. Thanks!
